### ISSUE TITLE
Cyclically `hl-find-thing`

### ISSUE THREAD

**Issue by hbin** [boyw165/hl-anything#13]
Hi boyw165,

I think cyclically `hl-find-thing` maybe more convenient. We can make this customizable.

**Comment by boyw165** [comment]
Ok, I'll update it later. I'm currently working on a queue-like searching framework for Emacs.

**Comment by boyw165** [comment]
Hi @hbin 

Check this out. https://github.com/boyw165/hl-anything/commit/a5fa386d3d4b77c138150e8f4a22f655ff98bfc3

**Comment by boyw165** [comment]
Hi @hbin 

Just fix issue of searching previous thing, plz check the latest repo.
