### ISSUE TITLE
Performance degradation when adding/removing highlighting after use of defadvice

### ISSUE THREAD

**Issue by kaushalmodi** [boyw165/hl-anything#9]
Hi,

I have been using this package ever since it was added to Melpa.

I started seeing a drastic performance degradation ever since [commit 18dc343b67890240a9bc36a163f3c006cb74b9b0](https://github.com/boyw165/hl-anything/commit/18dc343b67890240a9bc36a163f3c006cb74b9b0). 

When I manually downloaded an older version [commit bc93e67113be49cbe6a5892a9b8253f2814566a5](https://github.com/boyw165/hl-anything/commit/bc93e67113be49cbe6a5892a9b8253f2814566a5), the performance became excellent just as before.

When using commit **bc93e6**, adding and removing highlights is instant.
When using commit **18dc34**, adding and removing hightlights takes 4-5 seconds, I even see that "processing circle icon" in emacs while it is figuring out which highlights have to be added or removed.

I have roughly 100 buffers open at any time. I use `M-x hl-highlight-thingatpt-global` to add highlights and `M-x hl-unhighlight-all-global` to remove highlights.

I am using emacs 24.4 stable.

**Comment by boyw165** [comment]
Hi @kaushalmodi ,

I see. I think it might be 100 buffers. Thanks for your feedback, I'll fix it as soon as possible.

**Comment by boyw165** [comment]
Hi @kaushalmodi 

I think [33d51a0b](https://github.com/boyw165/hl-anything/commit/1ab03259485467a40c6e73ca7656ac0f33d51a0b) has fixed it.

**Comment by kaushalmodi** [comment]
Thanks. This issue is now fixed for me.
I use a combination of the `desktop` and `projectile` packages to manage multiple buffers per project.
Links: [my desktop setup](https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-desktop.el), [my projectile setup](https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-projectile.el)

Thank you for developing and maintaining this package; it has been very useful to me.
